<?php

define('PIN_ICONS', array(
  1 => 'sun',
  2 => 'moon',
  3 => 'bolt',
  4 => 'snowflake',
  5 => 'tint',
  6 => 'cloud-rain',
  7 => 'seedling',
  8 => 'tree',
  9 => 'fish',
  10 => 'cat',
  11 => 'horse',
  12 => 'crow',
  13 => 'apple-alt',
  14 => 'carrot',
  15 => 'pepper-hot',
  16 => 'lemon',
  17 => 'coffee',
  18 => 'beer',
  19 => 'store-alt',
  20 => 'couch',
  21 => 'tractor',
  22 => 'bicycle',
  23 => 'paper-plane',
  24 => 'anchor',
  25 => 'heart',
  26 => 'smile',
  27 => 'music',
  28 => 'key',
  29 => 'hourglass-half',
  30 => 'umbrella',
  31 => 'tools',
  32 => 'pen',
));