<div id="keyboard" style="display:none">
  <div id="keyboard_window">
    <div id="keyboard_header">
      <div class="button" onclick="keyboard_prev_input()"><span><i class="fa-solid fa-caret-left"></i></span></div>
      <div id="keyboard_info"></div>
      <div class="button" onclick="keyboard_next_input()"><span><i class="fa-solid fa-caret-right"></i></span></div>
    </div>
    <div id="keyboard_numbers" class="keyboard_keys keyboard_sub">
      <div>
        <div onclick="keyboard_key('1')"><span>1</span></div>
        <div onclick="keyboard_key('2')"><span>2</span></div>
        <div onclick="keyboard_key('3')"><span>3</span></div>
      </div>
      <div>
        <div onclick="keyboard_key('4')"><span>4</span></div>
        <div onclick="keyboard_key('5')"><span>5</span></div>
        <div onclick="keyboard_key('6')"><span>6</span></div>
      </div>
      <div>
        <div onclick="keyboard_key('7')"><span>7</span></div>
        <div onclick="keyboard_key('8')"><span>8</span></div>
        <div onclick="keyboard_key('9')"><span>9</span></div>
      </div>
      <div>
        <div onclick="keyboard_key(',')"><span>,</span></div>
        <div onclick="keyboard_key('0')"><span>0</span></div>
        <div class="none" onclick="return;keyboard_key('Hide')"><span><i class="fa-regular fa-eye-slash"></i></span></div>
      </div>
    </div>
    <div id="keyboard_options" class="keyboard_keys keyboard_sub">
      <?php //options are generated by main.js keyboard_show() ?>
    </div>
    <div id="keyboard_string_upper" class="keyboard_keys keyboard_sub">
      <?php
        $keys = array(
          array('!','"','§','$','%','&','/','(',')','=','?'),
          array('Q','W','E','R','T','Z','U','I','O','P','Ü'),
          array('A','S','D','F','G','H','J','K','L','Ö','Ä'),
          array('Y','X','C','V','B','N','M',';',':','_',' '),
        );
      ?>
      <?php foreach($keys as $keyrow): ?>
        <div>
          <?php foreach($keyrow as $key): ?>
            <div onclick="keyboard_key('<?php echo $key ?>')"><span><?php echo $key ?></span></div>
          <?php endforeach ?>
        </div>
      <?php endforeach ?>
    </div>
    <div id="keyboard_string_lower" class="keyboard_keys keyboard_sub">
      <?php
        $keys = array(
          array('1','2','3','4','5','6','7','8','9','0','ß'),
          array('q','w','e','r','t','z','u','i','o','p','ü'),
          array('a','s','d','f','g','h','j','k','l','ö','ä'),
          array('y','x','c','v','b','n','m',',','.','-',' '),
        );
      ?>
      <?php foreach($keys as $keyrow): ?>
        <div>
          <?php foreach($keyrow as $key): ?>
            <div onclick="keyboard_key('<?php echo $key ?>')"><span><?php echo $key ?></span></div>
          <?php endforeach ?>
        </div>
      <?php endforeach ?>
    </div>
    <div id="keyboard_ctrl" class="keyboard_keys">
      <div>
        <div id="key_shift" onclick="keyboard_key('Shift')"><span><i class="fa-regular fa-square-caret-up"></i></span></div>
        <div onclick="keyboard_key('Backspace')"><span><i class="fa-solid fa-delete-left"></i></span></div>
        <div class="none" onclick="return;keyboard_key('Undo')"><span><i class="fa-solid fa-rotate-left"></i></span></div>
        <div onclick="keyboard_key('Ok')"><span><i class="fa-solid fa-check"></i></i></span></div>
      </div>
    </div>
  </div>
</div>